# Generated by Django 3.2.17 on 2023-02-25 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="user_created",
            field=models.ForeignKey(
                help_text="Creator (author)", on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
